version: '3.8'
services:

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    network_mode: bridge
    expose:
      - 80
    ports:
      - "58080:80"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=wechaty.js.org
      - LETSENCRYPT_HOST=wechaty.js.org
